spring.application.name=Hacktualidad
spring.datasource.url=jdbc:mysql://localhost:3306/hacktualidad_bd?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
file.upload-dir=./uploads/

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=2juanvicenterodriguez@gmail.com
spring.mail.password=gqzf ycoe vsmm wtjl

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#swagger: http://localhost:8080/swagger-ui/index.html

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=hacktualidad-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.Hacktualidad.dto

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=60000

server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax

cloudinary.cloud-name=dqkv5bmt1
cloudinary.api-key=311116265369515
cloudinary.api-secret=Kjmlt58WeO3x-He-mUi4jZt1IJ0